name: flutter_skeleton
description: Flutter skeleton screen for Android and iOS. Support List, Card and Card-List style. Support light and dark theme.
version: 1.0.0+2

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=0.4.1 <2.0.0"
